(package "apache-mode"
         "2.2.0"
         "Major mode for editing Apache httpd configuration files")

(website-url "https://github.com/emacs-php/apache-mode")
(keywords "languages" "faces")

(package-file "apache-mode.el")

(script "test" "echo \"Error: no test specified\" && exit 1")

(source 'gnu)

(depends-on "emacs" "26.1")

(setq network-security-level 'low)  ; see https://github.com/jcs090218/setup-emacs-windows/issues/156#issuecomment-932956432
